//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest_Services
    {
        public int id { get; set; }
        public Nullable<int> reservation_id { get; set; }
        public Nullable<int> service_id { get; set; }
        public int quantity { get; set; }
        public string status { get; set; }
    
        public virtual Reservations Reservations { get; set; }
        public virtual Services Services { get; set; }
    }
}
