//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistics_hotel
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<decimal> occupancy_rate { get; set; }
        public Nullable<decimal> adr { get; set; }
        public Nullable<decimal> revpar { get; set; }
        public Nullable<decimal> revenue { get; set; }
    }
}
